services:
  php:
    build:
      args:
        user: asesora
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www/app
    networks:
      - red
  nginx:
    image: nginx:1.27.0-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - red

networks:
  red:
    driver: bridge